language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.2
  - DJANGO=1.4.1

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sleep 3 # give Web server some time to bind to sockets, etc

# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r conf/requirements.txt --use-mirrors
# command to run tests
script:
  - python manage.py test photo_manager --settings=settings.local
