language: python
python:
  - "2.6"
  - "2.7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sleep 3 # give Web server some time to bind to sockets, etc

# command to install dependencies
install:
  - pip install requirements.txt

script:
  - ./run_tests.sh
# command to run tests

