---

- name: Install MySQL Packages
  apt: pkg={{ item }} state=installed
  with_items:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python-mysqldb


- name: Create MySQL DB
  mysql_db: name=fotochest_dev state=present

- name: Establish MySQL User
  mysql_user: name=fotochest password=12345 priv=*.*:ALL state=present
