---

- name: install basic python packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python3.4-dev
    - python-virtualenv
    - python-crypto
    - python-setuptools
    - libxml2-dev
    - libyaml-dev
    - libpq-dev
    - libpq5
    - python-pip
    - libxslt-dev

- include: images.yml

- name: Install Virtualenvwrapper
  pip: name=virtualenvwrapper

- name: Build Project Virtualenvs
  command: virtualenv --python=python3 /home/vagrant/.virtualenvs/fotochest creates=/home/vagrant/.virtualenvs/fotochest

- name: Setup Virtualenv Dirs
  file: path=/home/vagrant/.virtualenvs state=directory owner=vagrant group=vagrant

- name: Ownership of Virtualenvs
  file: path=/home/vagrant/.virtualenvs/fotochest owner=vagrant group=vagrant recurse=True

- name: Setup Virtualenv Projects
  shell: . /usr/local/bin/virtualenvwrapper.sh && setvirtualenvproject /home/vagrant/.virtualenvs/fotochest /home/vagrant/fotochest
  args:
    executable: /bin/bash
  with_items: projects
  ignore_errors: True