---

- name: install basic python packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python2.7-dev
    - python-virtualenv
    - python-crypto
    - python-setuptools
    - libxml2-dev
    - libyaml-dev
    - libpq-dev
    - libpq5
    - python-pip
    - libxslt-dev

- include: images.yml


- name: Build Project Virtualenvs
  command: virtualenv /home/vagrant/.virtualenvs/fotochest creates=/home/vagrant/.virtualenvs/fotochest

- name: Setup Virtualenv Dirs
  file: path=/home/vagrant/.virtualenvs state=directory owner=vagrant group=vagrant

- name: Ownership of Virtualenvs
  file: path=/home/vagrant/.virtualenvs/fotochest owner=vagrant group=vagrant recurse=True
