---

- name: Install supervisor
  apt: pkg=supervisor state=installed

- name: Copy supervisor.conf
  notify:
  - Restart Supervisor
  template: src=roles/web/files/supervisord.conf dest=/etc/supervisord.conf owner=root mode=644